resolves #224
dask/helm-chart pull request #225
Opened 2022-02-07 15:12 UTC by desy-hh

updates ingress api version and its spec in the schduler webUI ingress template for current k8s versions.

2022-02-07 15:13 UTC, consideRatio commented
I believe there may be two separate ingress resources defined in this Helm chart, can you make the update for both?

2022-02-07 15:19 UTC, consideRatio commented on dask/templates/dask-scheduler-ingress.yaml
> +          pathType: {{ .Values.webUI.ingress.pathType | default "ImplementationSpecific" }}
Let's not use a default value hardcoded in this template, but instead let it be part of values which needs a new entry for this.

I also think maybe Prefix is what makes most sense here?

2022-02-07 15:37 UTC, desy-hh commented
> Hey @desy-hh maybe you could also add testing on a more modern version of k8s as well by updating the github workflow - that would validate that what you have done works I think.

Ok I added the 1.22 channel @consideRatio

2022-02-16 11:22 UTC, jacobtomlinson requested changes
Looks like this PR is ready but just needs the linters run.

Could you [run the linters](https://github.com/dask/helm-chart/blob/main/CONTRIBUTING.md#pre-commit)?

```
$ pip install pre-commit
$ pre-commit install
$ pre-commit run --all-files
```

2022-03-29 17:33 UTC, merged

2022-03-29 17:34 UTC, consideRatio commented
I'll fix pre-commit failures in another PR!

Thank you @desy-hh!!